"""empty message

Revision ID: 9d49c74567f4
Revises: 95ef0a7fd0ad
Create Date: 2020-11-29 15:39:33.458925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d49c74567f4'
down_revision = '95ef0a7fd0ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produce',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.Column('Number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_produce_ID'), 'produce', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produce_ID'), table_name='produce')
    op.drop_table('produce')
    # ### end Alembic commands ###
